version: "3.3"
services:
    singidunum-rest:
      image: razvoj.jar:latest
      restart: on-failure
      environment:
        - "spring.data.mongodb.uri=mongodb://root:test@singidunum-mongo:27056/test?authSource=admin&authMechanism=SCRAM-SHA-1"
      ports:
        - "9093:9093"
      stdin_open: true
      tty: true
      depends_on:
        - singidunum-mongo
    singidunum-mongo:
      image: mongo:4.2.0
      command: mongod --port 27056
      ports:
        - "27056:27056"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=test
        - MONGO_INITDB_DATABASE=test
      volumes:
        - mongodb_data_container:/data/db
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo localhost:27056/test --quiet
        interval: 10s
        timeout: 10s
        retries: 3
volumes:
  mongodb_data_container:
